### ISSUE TITLE
error init.csv

### ISSUE THREAD

**Issue by maximilien1990** [tehw0lf/airbash#24]
i get this error why? 

airba.sh: line 144: /home/max/tools/airbash/initlist-01.csv: No such file or directory
airba.sh: line 148: /home/max/tools/airbash/initlist-01.csv: No such file or directory

**Comment by tehw0lf** [comment]
These lines are trying to read the initial scan file, but apparently there is no file.

Maybe there were no candidates in range, so aircrack did not generate a file.
