### ISSUE TITLE
Exporting the hccap?

### ISSUE THREAD

**Issue by barrett092** [tehw0lf/airbash#3]
Is there a way you can export the captured handshake for manual cracking?

**Comment by tehw0lf** [comment]
All captured handshakes are saved to .hs/ in the airbash installation directory. To crack them manually you can copy them elsewhere or use hashcat with the path to the hccapx file.

**Comment by tehw0lf** [comment]
Since this issue seems to be solved, I am going to close it. Feel free to reopen if needed.
